#####################################################
################# EXPLANATION #######################
#
# This file and other configuration files are provided
# to create Hamilton specific functionality. While also
# providing interHamilton compatability for methods.
#
# This configuration file is used for deck loading.
# The Python script will read this file and, based
# on the volumes used for both plates and solutions,
# will autoload the deck for the Hamilton.
#
# This file is the lowest priority in the loading
# sequence. Thusly, this file is referenced when all 
# other deck loading protocols are exhausted.
#
#
#####################################################
#####################################################

Steps:
  Desalt:
    Preferred Loading:
      Waste: 
        - Carrier38_Pos1_96WellPCRPlate2000uL_1mLChannel
      Buffer: 
        - T4
      Destination: 
        - Carrier38_Pos5_96WellPCRPlate1200uL_1mLChannel
    Type:
      SizeX:
        100:
          Total Buffer Volume: 1000
